apps/blog/urls.py
# -*- coding: utf-8 -*-
__author__ = 'buzz'
__date__ = '2017/12/11 下午7:20'

from django.conf.urls import url

from . import views
from blog.feeds import AllPostsRssFeed

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.tag, name='tag'),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^blog_list/$', views.blog_list, name='blog-list'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
]

apps/comments/urls.py
# -*- coding: utf-8 -*-
__author__ = 'buzz'
__date__ = '2017/12/12 下午8:10'

from django.conf.urls import url

from . import views


app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

zly_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

from .settings import MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^search/', include('haystack.urls')),

]

apps/blog/models.py
import markdown

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.html import strip_tags


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)  # 文章摘要
    # 阅读量
    views = models.PositiveIntegerField(default=0)
    ## 外键
    # 一篇文章只有一个分类，一个分类下可有多个分类
    category = models.ForeignKey(Category)
    # 一篇文章可以有多个标签，一个标签下可以有多个文章
    tags = models.ManyToManyField(Tag, blank=True)
    # 一篇文章只有一个作者
    author = models.ForeignKey(User)

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 自定义save方法
    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super(Post, self).save(*args, **kwargs)


class Contact(models.Model):
    name = models.CharField(max_length=25)
    email = models.EmailField(max_length=255)
    subject = models.CharField(max_length=200)
    message = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "联系信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.message[:20]

apps/comments/models.py
from django.db import models


# Create your models here.

class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

apps/blog/forms.py
# -*- coding: utf-8 -*-
__author__ = 'buzz'
__date__ = '2017/12/13 下午3:56'

from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
            'subject': forms.TextInput(attrs={'placeholder': 'Subject'}),
            'message': forms.Textarea(attrs={'placeholder': 'Your Message'}),
        }

apps/blog/views.py
import markdown

from django.shortcuts import render, get_object_or_404
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension

from .models import Post, Category, Tag, Contact
from comments.forms import CommentForm
from .forms import ContactForm
from utils.send_email import send


# Create your views here.


def index(request):
    post_list = Post.objects.all().order_by('-created_time')

    # page
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    p = Paginator(post_list, 5, request=request)

    posts = p.page(page)

    return render(request, 'blog/index.html', context={'post_list': posts})


def blog_list(request):
    post_list = Post.objects.all().order_by('-created_time')

    # page
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    p = Paginator(post_list, 5, request=request)

    posts = p.page(page)

    return render(request, 'blog/full-width.html', context={'post_list': posts})


def about(request):
    return render(request, 'blog/about.html')


def contact(request):
    msg = ''
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            ct = form.save()
            # send email
            send(flag=2, nickname=ct.name, semail=ct.email, text=ct.message)
            msg = 'Success'
            form.clean()
    form = ContactForm()
    return render(request, 'blog/contact.html', {'form': form, 'msg': msg})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 阅读量 +1
    post.increase_views()

    # Markdown codehilite语法高亮，toc生成目录
    # post.body = markdown.markdown(
    #     post.body,
    #     extensions=[
    #         'markdown.extensions.extra',
    #         'markdown.extensions.codehilite',
    #         'markdown.extensions.toc',
    #     ]
    # )
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        # 'markdown.extensions.toc',
        TocExtension(slugify=slugify),
    ])
    post.body = md.convert(post.body)
    post.toc = md.toc

    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {
        'post': post,
        'form': form,
        'comment_list': comment_list
    }

    return render(request, 'blog/detail.html', context=context)


def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')
    # page
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    p = Paginator(post_list, 7, request=request)

    posts = p.page(page)
    return render(request, 'blog/index.html', context={'post_list': posts})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    p = Paginator(post_list, 7, request=request)

    posts = p.page(page)
    return render(request, 'blog/index.html', context={'post_list': posts})


def tag(request, pk):
    tag = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=tag).order_by('-created_time')
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    p = Paginator(post_list, 7, request=request)

    posts = p.page(page)
    return render(request, 'blog/index.html', context={'post_list': posts})

templates/blog/about.html
{% extends 'base-other.html' %}
{% load staticfiles %}

{% block content-body %}
<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="{% static 'img/me.jpg' %}" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="twitter"><a href="#"><span class="ion-social-twitter">Email</span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter">Weibo</span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
{% endblock %}

templates/blog/contact.html
{% extends 'base-other.html' %}

{% block content-body %}
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                <h1 class="page-title">Contact</h1>
                <article class="post">
                    <div class="entry-content clearfix">
                        <form action="." method="post" class="contact-form">
                            <div class="row">
                                {% if msg %}
                                    <div class="col-md-6 col-md-offset-3">
                                        <p>{{ msg }}</p>
                                    </div>
                                {% endif %}
                                <div class="col-md-6 col-md-offset-3">
                                    {{ form.name }}
                                    {{ form.name.errors }}
                                    {{ form.email }}
                                    {{ form.email.errors }}
                                    {{ form.subject }}
                                    {{ form.subject.errors }}
                                    {{ form.message }}
                                    {{ form.message.errors }}
                                    {% csrf_token %}
                                    <button class="btn-send btn-5 btn-5b ion-ios-paperplane" type="submit"><span>Drop Me a Line</span>
                                    </button>
                                </div>
                            </div>    <!-- row -->
                        </form>
                    </div>
                </article>
            </main>
        </div>
    </div>
{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a
                        href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">{{ comment_list.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body | safe }}
        </div>
    </article>

    <div class="entry-meta">
        <u>标签：</u>
        {% for tag in post.tags.all %}
            <span>
                    <a href="{% url 'blog:tag' tag.pk %}">#{{ tag.name }}&nbsp;&nbsp;</a>
                </span>
        {% endfor %}
    </div>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">网址：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                    {% csrf_token %}
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ comment_list.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                    <li class="comment-item">
                        <span class="nickname">{{ comment.name }}</span>
                        <time class="submit-date">{{ comment.created_time }}</time>
                        <div class="text">
                            {{ comment.text }}
                        </div>
                    </li>
                {% empty %}
                    暂无评论!
                {% endfor %}

            </ul>
        </div>
    </section>
{% endblock %}

{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc | safe }}
    </div>
{% endblock %}

templates/blog/full-width.html
{% extends 'base-other.html' %}

{% block content-body %}
    <div class="container">
        <div class="row">

            <main class="col-md-12">
                {% for post in post_list.object_list %}
                    <article class="post post-{{ post.pk }}">
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="post-category"><a
                                        href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>

                                <span class="post-date"><a href="#"><time class="entry-date"
                                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>

                                <span class="post-author"><a href="#">{{ post.author }}</a></span>

                                <span class="comments-link"><a href="#">{{ post.comment_set.count }} Comments</a></span>
                                <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            <p>{{ post.excerpt }}...</p>
                            <div class="read-more cl-effect-14">
                                <a href="{{ post.get_absolute_url }}" class="more-link">Continue reading <span
                                        class="meta-nav">→</span></a>
                            </div>
                        </div>
                    </article>
                {% empty %}
                    暂时没有发布文章！
                {% endfor %}

            <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination">
        <ul>
            {% if post_list.has_previous %}
                <li><a href="?{{ post_list.previous_page_number.querystring }}">上一页</a></li>
            {% endif %}

            {% for page in post_list.pages %}
                {% if page %}
                    {% ifequal page post_list.number %}
                        <li class="current"><a href="{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li><a href="">...</a></li>
                {% endif %}
            {% endfor %}

            {% if post_list.has_next %}
                <li><a href="?{{ post_list.next_page_number.querystring }}">下一页</a></li>
            {% endif %}

        </ul>
    </div>

            </main>
        </div>
    </div>


{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list.object_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a
                            href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}...</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">Continue reading <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>

    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>

    {% endfor %}



    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    <div class="pagination">
        <ul>
            {% if post_list.has_previous %}
                <li><a href="?{{ post_list.previous_page_number.querystring }}">上一页</a></li>
            {% endif %}

            {% for page in post_list.pages %}
                {% if page %}
                    {% ifequal page post_list.number %}
                        <li class="current"><a href="{{ page.querystring }}">{{ page }}</a></li>
                    {% else %}
                        <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li><a href="">...</a></li>
                {% endif %}
            {% endfor %}

            {% if post_list.has_next %}
                <li><a href="?{{ post_list.next_page_number.querystring }}">下一页</a></li>
            {% endif %}

        </ul>
    </div>
{% endblock main %}